In [1]:
import pandas as pd
import numpy as np

KAGGLE_DATASET_PATH = "../data/raw/Airbnb_Data.csv"
SCRAPED_DATASET_PATH = "../data/raw/scraped_airbnb_listings.csv"
MRGED_DATASET_PATH = "../data/merged/merged_airbnb_data.csv"

In [2]:
kaggle_df = pd.read_csv(KAGGLE_DATASET_PATH)
kaggle_df.head()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

In [3]:
scraped_df = pd.read_csv(SCRAPED_DATASET_PATH)
scraped_df.head()

,city,property_type,neighbourhood,listing_url,room_type,guests,bedrooms,beds,bathrooms,bathroom_type,price_per_night,rating,review_count,latitude,longitude,is_superhost,host_response_rate,host_identity_verified,free_cancellation,amenities
0,"Los Angeles, CA, USA",Home,Malibu,https://www.airbnb.com/rooms/1596739057740115269,Entire home,8.0,2.0,5.0,2.0,private,1258,5.00,39.0,34.06684,-118.67309,True,100.0,True,False,"Bathtub, Hair dryer, Cleaning products, Shampo..."
1,"Los Angeles, CA, USA",Apartment,Vernon,https://www.airbnb.com/rooms/1640195326455382137,Entire rental unit,3.0,1.0,2.0,1.0,private,291,4.77,2.0,34.01345,-118.23624,True,100.0,True,False,"Valley view, City skyline view, Bathtub, Hair ..."
2,"Los Angeles, CA, USA",Home,Los Angeles,https://www.airbnb.com/rooms/1220699370253252798,Entire home,10.0,4.0,8.0,3.0,private,500,5.00,1.0,34.18719,-118.37326,False,100.0,True,False,"Garden view, Hair dryer, Cleaning products, Sh..."
3,"Los Angeles, CA, USA",Tiny home,Topanga,https://www.airbnb.com/rooms/984107417862937992,NaN,2.0,1.0,1.0,1.0,private,314,4.96,290.0,34.07873,-118.60588,True,100.0,True,False,"Shampoo, Conditioner, Body soap, Outdoor showe..."
4,"Los Angeles, CA, USA",Home,Los Angeles County,https://www.airbnb.com/rooms/1590928612173170115,Entire home,4.0,3.0,3.0,3.0,private,377,5.00,7.0,34.09098,-118.60125,False,100.0,True,False,"Bathtub, Hair dryer, Cleaning products, Shampo..."

In [5]:
kaggle_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      74111 non-null  int64
 1   log_price               74111 non-null  float64
 2   property_type           74111 non-null  str
 3   room_type               74111 non-null  str
 4   amenities               74111 non-null  str
 5   accommodates            74111 non-null  int64
 6   bathrooms               73911 non-null  float64
 7   bed_type                74111 non-null  str
 8   cancellation_policy     74111 non-null  str
 9   cleaning_fee            74111 non-null  bool
 10  city                    74111 non-null  str
 11  description             74111 non-null  str
 12  first_review            58247 non-null  str
 13  host_has_profile_pic    73923 non-null  str
 14  host_identity_verified  73923 non-null  str
 15  host_response_rate      55812 non-null  str
 16  host_since              73923 non-null  str
 17  instant_bookable        74111 non-null  str
 18  last_review             58284 non-null  str
 19  latitude                74111 non-null  float64
 20  longitude               74111 non-null  float64
 21  name                    74111 non-null  str
 22  neighbourhood           67239 non-null  str
 23  number_of_reviews       74111 non-null  int64
 24  review_scores_rating    57389 non-null  float64
 25  thumbnail_url           65895 non-null  str
 26  zipcode                 73145 non-null  str
 27  bedrooms                74020 non-null  float64
 28  beds                    73980 non-null  float64
dtypes: bool(1), float64(7), int64(3), str(18)
memory usage: 15.9 MB

In [9]:
scraped_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   city                    1000 non-null   str
 1   property_type           1000 non-null   str
 2   neighbourhood           966 non-null    str
 3   room_type               954 non-null    str
 4   accommodates            893 non-null    float64
 5   bedrooms                917 non-null    float64
 6   beds                    951 non-null    float64
 7   bathrooms               965 non-null    float64
 8   bathroom_type           965 non-null    str
 9   price                   1000 non-null   int64
 10  review_scores_rating    993 non-null    float64
 11  number_of_reviews       993 non-null    float64
 12  latitude                998 non-null    float64
 13  longitude               998 non-null    float64
 14  host_response_rate      944 non-null    float64
 15  host_identity_verified  1000 non-null   bool
 16  amenities               999 non-null    str
 17  id                      1000 non-null   int64
dtypes: bool(1), float64(9), int64(2), str(6)
memory usage: 133.9 KB

In [ ]:
# Extract ID from URL
scraped_df['id'] = scraped_df['listing_url'].str.extract(r'/rooms/(\d+)')[0].astype(np.int64)

# Drop unnecessary columns
scraped_df = scraped_df.drop(columns=['listing_url', 'is_superhost', 'free_cancellation'])

# Rename columns to match Kaggle
scraped_df = scraped_df.rename(columns={
    'guests': 'accommodates',
    'rating': 'review_scores_rating',
    'review_count': 'number_of_reviews',
    'price_per_night': 'price'
})

In [11]:
scraped_df.head()

,city,property_type,neighbourhood,room_type,accommodates,bedrooms,beds,bathrooms,bathroom_type,price,review_scores_rating,number_of_reviews,latitude,longitude,host_response_rate,host_identity_verified,amenities,id
0,"Los Angeles, CA, USA",Home,Malibu,Entire home,8.0,2.0,5.0,2.0,private,1258,5.00,39.0,34.06684,-118.67309,100.0,True,"Bathtub, Hair dryer, Cleaning products, Shampo...",1596739057740115269
1,"Los Angeles, CA, USA",Apartment,Vernon,Entire rental unit,3.0,1.0,2.0,1.0,private,291,4.77,2.0,34.01345,-118.23624,100.0,True,"Valley view, City skyline view, Bathtub, Hair ...",1640195326455382137
2,"Los Angeles, CA, USA",Home,Los Angeles,Entire home,10.0,4.0,8.0,3.0,private,500,5.00,1.0,34.18719,-118.37326,100.0,True,"Garden view, Hair dryer, Cleaning products, Sh...",1220699370253252798
3,"Los Angeles, CA, USA",Tiny home,Topanga,NaN,2.0,1.0,1.0,1.0,private,314,4.96,290.0,34.07873,-118.60588,100.0,True,"Shampoo, Conditioner, Body soap, Outdoor showe...",984107417862937992
4,"Los Angeles, CA, USA",Home,Los Angeles County,Entire home,4.0,3.0,3.0,3.0,private,377,5.00,7.0,34.09098,-118.60125,100.0,True,"Bathtub, Hair dryer, Cleaning products, Shampo...",1590928612173170115

In [8]:
# Drop unnecessary columns
kaggle_df = kaggle_df.drop(columns=[
    'bed_type', 'cancellation_policy', 'cleaning_fee', 'description', 'first_review',
    'host_has_profile_pic', 'host_since', 'instant_bookable', 'last_review',
    'name', 'thumbnail_url', 'zipcode'
])

# Transform log_price back to linear scale
kaggle_df['price'] = np.exp(kaggle_df['log_price'])
kaggle_df = kaggle_df.drop(columns=['log_price'])

# Scale review_scores_rating from 0-100 to 0-5
kaggle_df['review_scores_rating'] = kaggle_df['review_scores_rating'] / 20

In [9]:
# Get Kaggle columns after transformation
columns_order = kaggle_df.columns.tolist()

# Reorder scraped_df to match Kaggle
scraped_df = scraped_df[columns_order]

In [10]:
merged_df = pd.concat([kaggle_df, scraped_df], ignore_index=True)
merged_df.to_csv(MRGED_DATASET_PATH, index=False)
print("File saved successfully.")
print(merged_df.info())

File saved successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75111 entries, 0 to 75110
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      75111 non-null  int64
 1   property_type           75111 non-null  object
 2   room_type               75065 non-null  object
 3   amenities               75110 non-null  object
 4   accommodates            75004 non-null  float64
 5   bathrooms               74876 non-null  float64
 6   city                    75111 non-null  object
 7   host_identity_verified  74923 non-null  object
 8   host_response_rate      56756 non-null  object
 9   latitude                75109 non-null  float64
 10  longitude               75109 non-null  float64
 11  neighbourhood           68205 non-null  object
 12  number_of_reviews       75104 non-null  float64
 13  review_scores_rating    58382 non-null  float64
 14  bedrooms                74937 non-null  float64
 15  beds                    74931 non-null  float64
 16  price                   75111 non-null  float64
dtypes: float64(9), int64(1), object(7)
memory usage: 9.7+ MB
None

In [11]:
merged_df.head()

,id,property_type,room_type,amenities,accommodates,bathrooms,city,host_identity_verified,host_response_rate,latitude,longitude,neighbourhood,number_of_reviews,review_scores_rating,bedrooms,beds,price
0,6901257,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3.0,1.0,NYC,t,NaN,40.696524,-73.991617,Brooklyn Heights,2.0,5.00,1.0,1.0,150.0
1,6304928,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7.0,1.0,NYC,f,100%,40.766115,-73.989040,Hell's Kitchen,6.0,4.65,3.0,3.0,169.0
2,7919400,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5.0,1.0,NYC,t,100%,40.808110,-73.943756,Harlem,10.0,4.60,1.0,3.0,145.0
3,13418779,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4.0,1.0,SF,t,NaN,37.772004,-122.431619,Lower Haight,0.0,NaN,2.0,2.0,750.0
4,3808709,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2.0,1.0,DC,t,100%,38.925627,-77.034596,Columbia Heights,4.0,2.00,0.0,1.0,115.0

In [12]:
merged_df.tail()

,id,property_type,room_type,amenities,accommodates,bathrooms,city,host_identity_verified,host_response_rate,latitude,longitude,neighbourhood,number_of_reviews,review_scores_rating,bedrooms,beds,price
75106,1271726495457576312,Home,Entire home,"Hair dryer, Cleaning products, Method organic ...",8.0,3.0,"Washington, DC, USA",True,100.0,38.99343,-77.04269,Washington,13.0,5.00,3.0,4.0,883.0
75107,8581470,Home,Entire home,"Garden view, Bathtub, Hair dryer, Cleaning pro...",10.0,2.0,"Washington, DC, USA",True,100.0,38.92719,-77.03077,Washington,192.0,4.72,5.0,7.0,810.0
75108,53919426,Guesthouse,Entire guesthouse,"Hair dryer, Cleaning products, Shampoo, Condit...",6.0,2.0,"Washington, DC, USA",True,100.0,38.88220,-76.99630,Washington,125.0,4.90,3.0,3.0,378.0
75109,34800811,Townhouse,Entire townhouse,"Bathtub, Hair dryer, Quality shampoo, Conditio...",12.0,2.0,"Washington, DC, USA",True,100.0,38.83430,-77.05270,Alexandria,278.0,4.79,3.0,7.0,375.0
75110,1642271407581334922,Hotel room,Room,"Hair dryer, Cleaning products, Shampoo, Condit...",8.0,1.0,"Washington, DC, USA",True,100.0,38.93277,-77.02491,Washington,1.0,4.90,3.0,4.0,302.0

# Useful for validation

In [12]:
kaggle_df["amenities"][1]

'{"Wireless Internet","Air conditioning",Kitchen,Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Fire extinguisher",Essentials,Shampoo,Hangers,"Hair dryer",Iron,"translation missing: en.hosting_amenity_50"}'

In [14]:
scraped_df["amenities"][1]

'Valley view, City skyline view, Bathtub, Hair dryer, Cleaning products, Shampoo, Hot water, Shower gel, Washer, Free dryer – In unit, Hangers, Bed linens, Extra pillows and blankets, Iron, Clothing storage, TV, Exercise equipment: elliptical, free weights, stationary bike, treadmill, yoga mat, Air conditioning, Heating, Exterior security cameras on property, Smoke alarm, Carbon monoxide alarm, Fire extinguisher, Wifi, Dedicated workspace, Kitchen, Refrigerator, Microwave, Cooking basics, Dishes and silverware, Freezer, Dishwasher, Stove, Stainless steel oven, Hot water kettle, Coffee maker, Wine glasses, Toaster, Trash compactor, Dining table, Coffee, Private patio or balcony, BBQ grill, Free residential garage on premises – 1 space, Pool, Hot tub, Elevator, EV charger - level 2, Shared gym in building, Paid parking garage on premises, Long term stays allowed, Self check-in, Lockbox, Unavailable: EssentialsEssentials'

In [15]:
print(kaggle_df["host_response_rate"][1])
print(type(kaggle_df["host_response_rate"][1]))

100%
<class 'str'>

In [16]:
print(scraped_df["host_response_rate"][1])
print(type(scraped_df["host_response_rate"][1]))

100.0
<class 'numpy.float64'>

In [13]:
def show_unique(column):
    kaggle_unique_values = kaggle_df[column].unique()
    scraped_unique_values = scraped_df[column].unique()
    print(f"Unique values in '{column}':")
    print(f"\nFOR KAGGLE DATASET:\n {kaggle_unique_values}")
    print(f"{30 * '-'}")
    print(f"\nFOR SCRAPED DATASET:\n {scraped_unique_values}\n")

In [15]:
attributes = ['room_type', 'city', 'host_identity_verified']
for attr in attributes:
    print(f"{60 * '#'}\n")
    show_unique(attr)

############################################################

Unique values in 'room_type':

FOR KAGGLE DATASET:
 <StringArray>
['Entire home/apt', 'Private room', 'Shared room']
Length: 3, dtype: str
------------------------------

FOR SCRAPED DATASET:
 <StringArray>
[                                                          'Entire home',
                                                    'Entire rental unit',
                                                                     nan,
                                                          'Entire villa',
                                                     'Entire guesthouse',
                                                          'Entire cabin',
                                             'Entire serviced apartment',
                                                    'Entire guest suite',
                                                          'Private room',
                                                        'Entire cottage',
                                                                  'Room',
                                                       'Entire bungalow',
                                  'Private RoomShareSaveShow all photos',
                                                      'Entire townhouse',
                                                          'Entire condo',
                                                          'Entire place',
 'Entire Oceanfront Home Breathtaking 180 ViewsShareSaveShow all photos',
                                                          'Private Room',
                                                  'Entire vacation home',
                                                           'Entire loft',
                                      'Private room, entrance &bathroom',
                                                   'Private room & bath']
Length: 22, dtype: str

############################################################

Unique values in 'city':

FOR KAGGLE DATASET:
 <StringArray>
['NYC', 'SF', 'DC', 'LA', 'Chicago', 'Boston']
Length: 6, dtype: str
------------------------------

FOR SCRAPED DATASET:
 <StringArray>
[  'Los Angeles, CA, USA', 'San Francisco, CA, USA',      'New York, NY, USA',
       'Chicago, IL, USA',    'Washington, DC, USA']
Length: 5, dtype: str

############################################################

Unique values in 'host_identity_verified':

FOR KAGGLE DATASET:
 <StringArray>
['t', 'f', nan]
Length: 3, dtype: str
------------------------------

FOR SCRAPED DATASET:
 [ True False]